spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/travel_booking
    username: root
    password: 2001
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true


travelbooking:
  app:
    jwtSecret: travelbookingapp
    jwtExpirationMs: 86400000